---
kind: pipeline
name: build

platform:
  os: linux
  arch: amd64

steps:
- name: assets
  image: node
  commands:
  - npm install -g gulp -s
  - npm install -s
  - gulp default

- name: test
  image: klakegg/hugo:0.59.1-ext-alpine
  commands:
  - cd exampleSite/ && ln -s ../../. themes/hugo-geekdoc && hugo-official

- name: build
  image: alpine
  commands:
  - mkdir dist/
  - tar -zcvf dist/hugo-geekdoc.tar.gz . --exclude='.git*' --exclude='.drone*' --exclude='dist' --exclude='.git*' --exclude='example*' --exclude='src' --exclude='gulp*' --exclude='package*' --exclude='node*'

- name: checksum
  image: alpine
  commands:
  - cd dist/ && sha256sum * > ../sha256sum.txt
  - cd ../ && ls -lh dist/
  - cat sha256sum.txt

- name: publish
  image: plugins/github-release
  settings:
    api_key:
      from_secret: github_token
    files:
    - dist/*
    - sha256sum.txt
    note: CHANGELOG.md
    overwrite: true
    title: ${DRONE_TAG}
  when:
    ref:
    - refs/tags/**

trigger:
  ref:
  - refs/heads/master
  - refs/tags/**
  - refs/pull/**

---
kind: pipeline
name: docs

platform:
  os: linux
  arch: amd64

steps:
- name: assets
  image: alpine
  commands:
  - mkdir -p exampleSite/themes/hugo-geekdoc/
  - curl -L https://github.com/xoxys/hugo-geekdoc/tarball/master | tar -xz -C exampleSite/themes/hugo-geekdoc/ --strip-components=1

- name: test
  image: klakegg/hugo:0.59.1-ext-alpine
  commands:
  - cd exampleSite/ && hugo-official

trigger:
  ref:
  - refs/heads/master

---
kind: signature
hmac: 045e419a618003df0ea0a85de97a8152d88192a7b9e6f5ad8ba2701913e6288f

...
