# hugo server --minify --themesDir ... --baseURL=http://0.0.0.0:1313

baseURL: https://docs.geeklabor.de/
title: Geekdoc
theme: hugo-geekdoc
pygmentsUseClasses: true
pygmentsCodeFences: true

# Geekdoc configuration
disablePathToLower: true
enableGitInfo: true

# Needed for mermaid/katex shortcodes
markup:
  goldmark:
    renderer:
      unsafe: true
  tableOfContents:
    startLevel: 1

params:
  geekdocToC: 3

  geekdocRepo: https://github.com/xoxys/hugo-geekdoc
  geekdocEditPath: edit/master/exampleSite/content

  geekdocDateFormat: "Jan 2, 2006"
  geekdocSearch: true
